### ISSUE TITLE
[BUG] AuthContext에서 유저로그인 상태가 제대로 확인이 안되는 버그

### ISSUE THREAD

**Issue by silverzoo** [CampingOn/CampingOn-FE#50]
### 📝 버그 요약

AuthContext에서 유저로그인 상태가 제대로 확인이 안되는 버그

### 🔄 재현 방법

1. 로그인페이지에서 로그인
3. 콘솔창을 확인
4. 메인페이지에서 새로고침
5. 콘솔창을 확인

### ✔️ 예상 동작

1. 로그인페이지에서 로그인
2. 메인페이지로 이동하자마자 로그인확인이 되었으니 헤더의 우측에 로그아웃 버튼이 띄워져야함

### ❌ 실제 동작

로그인 직후 액세스토큰이 잘 확인이되는데도 isAuthenticated는 false로 확인
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/37142160-20d6-4d31-877e-df4cb6ab7db5">
그리고 새로고침을 하면 2번 요청(strict mode 껐는데도 2번 요청이.. why?) 중 한번은 false, 이후 true 반환
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/5c419d6e-1308-40dd-ba12-5f7568fbd6f7">

**Comment by moonformeli** [comment]
네~, 이거는 아래와 같은 현상때문에 그런것으로 보입니다.

1. Header 컴포넌트의 24번 라인에서 `console.log('유저로그인상태', isAuthenticated);`를 호출하고 있는데요. 이 것 때문에 일단 무조건 처음에 `isAuthenticated` 의 값을 콘솔에 남기게 됩니다.

2. `isAuthenticated`는 AuthContext.js에서 온 값인데, 이 때의 `isAuthenticated`의 값은 다음의 라인때문에 false로 초기화가 되어요.
```js
const [isAuthenticated, setIsAuthenticated] = useState(false);
```
그래서 첫 콘솔은 false가 나오게 됩니다.

3. 이후, AuthContext.js의 다음의 코드가 실행되게 됩니다.
```js
useEffect(() => {
        const token = localStorage.getItem('accessToken');
        console.log('Access Token:', token);
        setIsAuthenticated(!!token);
    }, []);
```
이 곳에서 `isAuthenticated`가 true로 변경이 되는 것으로 보이네요.

4. AuthContext.js에서 사용하는 상태 값이 업데이트됨에 따라, Header 컴포넌트에서 사용중인 다음 라인이 영향을 받습니다.
```js
// 이제는 isAuthenticated는 true입니다.
const {isAuthenticated, logout} = useAuth();
```
상태 값이 변경되어서 Header 컴포넌트가 다시 실행되게 되고,
이때 `isAuthenticated`는 true이므로 두 번째 콘솔에서 true가 찍히게 되는 것으로 보입니다~

**Comment by silverzoo** [comment]
코치님 답변으로 2가지로 코드 수정을 했는데요.
1. `const [isAuthenticated, setIsAuthenticated] = useState(!!localStorage.getItem("accessToken"));` 로 바꿔서 초기값을 로컬스토리지의 상태값을 확인 후 바로 처리
2.  중복된 로그인 상태 확인을 방지하고자 isLoading 상태를 추가하여 상태가 확인 될때까지 기다리게 처리를 했는데요.
그런 덕분에 상태 체크가 여러번 일어나진 않는 것 같습니다.

그런데 여전히 로그인 후 리다이렉트 된 메인에서 새로고침을 한번 해주지 않으면 로그인 상태가 false로 확인이 되는데요.
![image](https://github.com/user-attachments/assets/943b0063-96f7-4fed-9222-ffedd14556f4)

혹시 preflight 요청을 허용하지 않아서 api 호출이 2번 일어난것과 연관이 있을까요? 사실 지금 거의 모든 페이지에서 preflight 요청 발생 후 진짜? 요청이 이루어지고 있는 상황입니다. 백엔드 쪽 CORS 설정에서 OPTIONS 메서드 허용, preflight 요청 허용을 해두어도 그렇습니다.. 
![image](https://github.com/user-attachments/assets/54728fe4-7b12-47a7-bdfa-076b6314406a)

**Comment by moonformeli** [comment]
> 코치님 답변으로 2가지로 코드 수정을 했는데요.
> 
> 1. `const [isAuthenticated, setIsAuthenticated] = useState(!!localStorage.getItem("accessToken"));` 로 바꿔서 초기값을 로컬스토리지의 상태값을 확인 후 바로 처리
> 2. 중복된 로그인 상태 확인을 방지하고자 isLoading 상태를 추가하여 상태가 확인 될때까지 기다리게 처리를 했는데요.
>    그런 덕분에 상태 체크가 여러번 일어나진 않는 것 같습니다.
> 
> 그런데 여전히 ...

저 것은 Login 컴포넌트를 보시면 로그인 완료 후에 `localStorage.setItem('accessToken', response.data.accessToken);` 이 작업만을 하고 바로 페이지를 이동하는데요, 로컬스토리지르 수정하더라도 코드 내에서 그것을 **자동으로 감지하지는 않기 때문에** 따로 추가 작업을 해주셔야 합니다.

AuthContext의 login 함수를 빼와서
```
localStorage.setItem('accessToken', response.data.accessToken);
login()
```
이렇게 해주면 될 것 같네요~~
